CREATE TABLE IF NOT EXISTS grupos_usuarios (
  id VARCHAR(50) PRIMARY KEY,
  nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
  id VARCHAR(30) PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  senha VARCHAR(200),
  grupo VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (grupo) REFERENCES grupos_usuarios(id)
);

CREATE TABLE IF NOT EXISTS log_usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_usuario VARCHAR(30),
  data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  acao VARCHAR(50)
);
